### ISSUE TITLE
Menu górne zawsze widoczne

### ISSUE THREAD

**Issue by Sieciechu** [Sieciechu/rebusuje#5]
Chcę, żeby menu górne wraz z logo było zawsze widoczne na ekranie, bez względu na przewijanie na stronie głównej i stronie wpisu.

**Comment by Sieciechu** [comment]
Pytanie: co z przewijaniem menu górnego podczas przeglądania na mobilnych (tabletach i komórkach) ?

**Comment by ralphsz** [comment]
Dodałem improvement, że po scrollu top nav się trochę zwęża.
![image](https://cloud.githubusercontent.com/assets/25901655/24037312/a7688506-0afd-11e7-9648-3e04494b9af6.png)
